# Generated by Django 3.0.1 on 2019-12-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poroject',
            new_name='Project',
        ),
    ]
